version: "3.0"
services:
    nginx:
        image: nginx
        container_name: nginx
        ports:
            - 80:80
        volumes:
            - ./build:/usr/share/nginx/src
            - ./conf/kwkaiser.io.conf:/etc/nginx/conf.d/default.conf
