version: "3.0"
services:
  swag:
    image: linuxserver/swag
    container_name: swag
    ports:
      - 80:80
      - 443:443

    environment:
      - URL=kwkaiser.io
      - SUBDOMAINS=www
      - EMAIL=karl@kwkaiser.io
      - VALIDATION=http
    volumes:
      - ./public:/config/www
