baseURL = 'https://kwkaiser.io/'
languageCode = 'en-us'
title = "Kaiser's site"

[module]
  [[module.imports]]
    path = 'github.com/lxndrblz/anatole'

[params]
title = ""
author = 'Karl Kaiser'

description = """
Some guy who does some code stuff
"""

profilePicture = "images/profile.jpg"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "github"
url = "https://github.com/kwkaiser"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:karl@kwkaiser.io"

[menu]
  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"