baseURL = 'https://kwkaiser.io/'
languageCode = 'en-us'
title = "Kaiser's site"

[module]
  [[module.imports]]
    path = 'github.com/lxndrblz/anatole'

[params]
title = ""
author = 'Karl Kaiser'
mainSections = []

description = """
Software engineer, neuroscience enthusiast, some other stuff here
"""

profilePicture = "images/profile.jpg"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "github"
url = "https://github.com/kwkaiser"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:karl@kwkaiser.io"

[menu]
  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 1 
  url = "/"

  [[menu.main]]
  name = "Experience"
  identifier = "experience"
  weight = 2
  url = "/experience"

  [[menu.main]]
  name = "Education"
  identifier = "education"
  weight = 3
  url = "/education"

  [[menu.main]]
  name = "Publications"
  identifier = "publications"
  weight = 4 
  url = "/publications"

  [[menu.main]]
  name = "Resume"
  identifier = "resume"
  weight = 5 
  url = "/resume.pdf"
