version: '3'

tasks:
  clean:
    cmds:
      - rm -rf public

  dev:
    cmds:
      - hugo server

  build:
    cmds:
      - rm -rf public
      - hugo

  build-docker:
    cmds:
      - docker build -t kwkaiser/website .

  deploy:
    deps: [build]
    cmds:
      - docker-compose up -d

  redeploy:
    deps: [build]
    cmds:
      - docker-compose down
      - docker-compose up -d