version: '3'

tasks:
  clean:
    cmds:
      - rm -rf mount

  secrets:
    prompt: Did you set the CLOUDFLARE_EMAIL and CLOUDFLARE_API_KEY envars?
    cmds:
      - mkdir -p mount
      - rm -f mount/cloudflare.ini
      - echo "dns_cloudflare_email=$CLOUDFLARE_EMAIL" >> mount/cloudflare.ini
      - echo "dns_cloudflare_api_key=$CLOUDFLARE_API_KEY" >> mount/cloudflare.ini

  dev:
    cmds:
      - hugo server

  build:
    cmds:
      - mkdir -p mount
      - rm -rf public
      - rm -rf mount/public
      - hugo
      - cp -r public mount/

  deploy:
    deps: [secrets, build]
    cmds:
      - docker-compose up -d

  redeploy:
    deps: [build]
    cmds:
      - docker-compose down
      - docker-compose up -d