server {
	listen 80 default_server;
	listen [::]:80 default_server;
	server_name kwkaiser.io;
	return 301 https://$host$request_uri;
}

server {
	listen 443 ssl http2 default_server;
	listen [::]:443 ssl http2 default_server;
    server_name kwkaiser.io;

	include /config/nginx/ssl.conf;
	include /config/nginx/proxy-confs/*.subfolder.conf;

	root /config/www;
	index home.html home.htm; 

	client_max_body_size 0;

    location / {
        if ($request_uri ~ ^/(.*)\.html) {
            return 302 /$1;
        }
        try_files $uri $uri.html $uri/ =404;

        root   /config/www;
        index  home.html home.htm;
    }
}
	    
