
server {
    gzip on;
    listen       80;
    listen  [::]:80;
    server_name  kwkaiser.io;


    location / {
        if ($request_uri ~ ^/(.*)\.html) {
            return 302 /$1;
        }
        try_files $uri $uri.html $uri/ =404;

        root   /usr/share/nginx/src;
        index  index.html index.htm;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
