version: "3.0"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    environment:
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezon:ro

  swag:
    image: linuxserver/swag
    container_name: swag
    ports:
      - 80:80
      - 443:443

    environment:
      - URL=kwkaiser.io
      - SUBDOMAINS=analytics
      - EMAIL=karl@kwkaiser.io
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
    volumes:
      - ../data/webserver-data/swag:/config

  umamidb:
    image: postgres
    container_name: umamidb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=umami

    volumes:
      - ../data/webserver-data/umami/:/var/lib/postgresql/data

  umami:
    container_name: umami
    image: ghcr.io/mikecao/umami:postgresql-latest
    depends_on:
      - umamidb
    environment:
      - DATABASE_URL=postgres://postgres:umami@umamidb:5432/postgres
